FROM ${IMAGE_PARENT}
LABEL maintainer ${MAINTAINER}

ADD rootfs.tar /

RUN mkdir -p /riemann-dash/config && \
    ln -s /usr/include/libxml2/libxml /usr/include/libxml && \
    gem install nokogiri -- --use-system-libraries --no-document && \
    gem install --no-document riemann-client riemann-tools riemann-dash

COPY config.rb /riemann-dash/

VOLUME ["/riemann-dash/config"]
WORKDIR /riemann-dash

EXPOSE 4567

CMD ["riemann-dash"]
