FROM ${IMAGE_PARENT}
LABEL maintainer ${MAINTAINER}

ONBUILD ARG JAVA_UID
ONBUILD ARG JAVA_GID
ONBUILD RUN if [ -n "$JAVA_UID" ] && [ -n "$JAVA_GID" ]; then \
              echo " ---> Set java uid ${JAVA_UID} and gid ${JAVA_GID}"; \
              sed-or-die '^java:x:[0-9]*:[0-9]*:' "java:x:${JAVA_UID}:${JAVA_GID}:" /etc/passwd; \
              sed-or-die '^java:x:[0-9]*:' "java:x:${JAVA_GID}:" /etc/group; \
              chown -R java:java /home/java ; fi

ADD rootfs.tar /

CMD ["/bin/bash"]
