FROM ${IMAGE_PARENT}
LABEL maintainer="${MAINTAINER}"

ADD rootfs.tar /

EXPOSE 8086

VOLUME ["/var/lib/influxdb/"]

HEALTHCHECK --interval=30s --timeout=3s CMD wget --spider http://localhost:8086/ping || exit 1

ENTRYPOINT ["/usr/bin/influxd"]
CMD ["--reporting-disabled"]

