FROM ${IMAGE_PARENT}
LABEL maintainer ${MAINTAINER}

ADD rootfs.tar /

ADD etc /etc

COPY docker-healthcheck.sh /usr/local/bin/

EXPOSE 5601

HEALTHCHECK --interval=30s --timeout=3s CMD docker-healthcheck.sh

RUN chown -R kibana:kibana /etc/kibana && \
    chmod +x $(find /etc/service -name run) && \
    ln -s /etc/s6_finish_default /etc/service/kibana/finish && \
    ln -s /etc/service/kibana /service

CMD ["/bin/s6-svscan", "-s", "-t0", "/service"]
